### ISSUE TITLE
Suggestion to move code to outside of "btree" folder

### ISSUE THREAD

**Issue by berosoboy** [fian46/addons-btree#2]
This helps to add the project directly as a git submodule on project's addons folder

**Comment by fian46** [comment]
I am not sure how to do this.

**Comment by berosoboy** [comment]
I was thinking to remove the "btree" folder, moving the contents to the repository root.
It helps on the plugin installation because we can download this repo and extract the zip directly on addon folder. I can do a PR if it's ok

**Comment by fian46** [comment]
PR are welcome

**Comment by berosoboy** [comment]
Alright. I will submit a PR soon.
By the way, you did a good job on this plugin. I'm glad to help

**Comment by berosoboy** [comment]
Do you have plans to publish this project to AssetLib?
According to [Godot docs](https://docs.godotengine.org/en/stable/tutorials/assetlib/using_assetlib.html#doc-using-assetlib), we just need to create a addons folder and put the btree folder inside it.
So it will be ready to publish in Asset Library and can be installed properly.

**Comment by fian46** [comment]
That is great maybe we can publish it some time in near future.

**Comment by fian46** [comment]
Fixed by #11

**Comment by shayneoneill** [comment]
It'd be good to see this in the asset library.  The other Behavior tree project there, whilst commendable has some fairly serious flaws (Including hard-coded paths to the authors hard drive), and this one seems to just work.
