### ISSUE TITLE
Nodes dissapear when changing panels in Godot,in version 1.1.0

### ISSUE THREAD

**Issue by davord45** [fian46/addons-btree#20]
Hey fian46,love your addon! My nodes seem to disappear when i move to a different panel like Script or 2d.
This was before fixed with saving while i was in the Tree Editor,but since this new version 1.1.0 this does not seem to work.
Did you change the way saving was done or is this a bug?
![image](https://user-images.githubusercontent.com/70846358/93142262-f6655080-f6e5-11ea-88fc-c3eeff2e69db.png)
![image](https://user-images.githubusercontent.com/70846358/93142475-61168c00-f6e6-11ea-83b6-678fe1899779.png)

I will be using the old version until this issue is fixed,but am excited to test out debugger when its working.

**Comment by fian46** [comment]
@davord45 can you give me the step to reproduce ? it is happened to me couple time back but i cannot reproduce it consistently.

**Comment by fian46** [comment]
so i found the bug. if a node is not connected to the root by some ways or another it will disappear when switch the editor. thank you for reporting the bug.

**Comment by fian46** [comment]
you can test the fix in release 1.1.1-alpha. i have tested it and working like before. i need your confirmation. @davord45

**Comment by davord45** [comment]
Now it works like before.They still disappear if its not saved,but that was also the case in the previous version.
Tried the debug and its working from what i can see.

![image](https://user-images.githubusercontent.com/70846358/93169410-54655880-f725-11ea-8698-8963378f4e54.png)

Thanks for fixing the issue!

**Comment by fian46** [comment]
You can use 1.1.1 release for latest version.
