### ISSUE TITLE
Allow Node renaming so that they can be distinguished in the debugging

### ISSUE THREAD

**Issue by davord45** [fian46/addons-btree#24]
Hi fian46.
Can you please add an option to rename nodes,or just tasks,cause right now they get generated names,like task1,task2.
Its hard to know in debugger which node is doing what.Otherwise you have to know your tree by heart.
![image](https://user-images.githubusercontent.com/70846358/93189141-1d517000-f742-11ea-9765-df61fbfa2801.png)

**Comment by davord45** [comment]
Or you dont even have to rename the nodes in the editor,just add a label for the debugger.

**Comment by fian46** [comment]
What if i just put function name that the task calling in the node ? Is it make more useful ?

**Comment by davord45** [comment]
Yeah thats the way it works in the editor,so i think it would work.

**Comment by davord45** [comment]
You can add that to all nodes that are referencing a function,like priority condition as well.

**Comment by davord45** [comment]
Could you also put the parameters that they are passing,if its not a big problem,like in the brackets or something

**Comment by fian46** [comment]
it fixed by [1.1.2-alpha](https://github.com/fian46/addons-btree/releases/tag/1.1.2-alpha)

**Comment by davord45** [comment]
Awesome,way better now.

**Comment by davord45** [comment]
Btw why dont you publish on Asset Library?
The addon will get more attention that way.

**Comment by fian46** [comment]
It still missing something and i don't know what it is. Maybe some more input can make it better. Can you help me publish it in asset library ?

**Comment by davord45** [comment]
Ill report if I find something that you can input.

https://docs.godotengine.org/en/stable/tutorials/assetlib/uploading_to_assetlib.html

I found this link that says how to publish on the Godot Asset library and the requirements. I don't have much experience in add-on development and publishing. With what exactly you need help with?
