### ISSUE TITLE
Latest save functionality commit broke save again.

### ISSUE THREAD

**Issue by davord45** [fian46/addons-btree#26]
Hey fian46,i tested your new commits,and it seems that saving is broken again.Nodes dissapear even when saved in the editor.Or in further inspection they dissapear only when saved,if not saved only not saved ones dissapear.
![slika](https://user-images.githubusercontent.com/70846358/93485844-cdbaa200-f903-11ea-862e-9c715e9cb6d2.png)
![slika](https://user-images.githubusercontent.com/70846358/93485869-d612dd00-f903-11ea-8bb7-ac8672dea5cc.png)
I see you are planning to release it on Asset Library.Hope you can fix that bug before than.

**Comment by fian46** [comment]
My bad. I am trying to make it auto saving the tree when switch window without user have to press save every single time. I have test it i seams working in my case but break yours. I ll check it again.

**Comment by davord45** [comment]
If you can make it working that would be awesome.

**Comment by davord45** [comment]
Could you also make it save on running?Or whenever save is pressed elsewhere.

**Comment by fian46** [comment]
save on running you mean it auto sync the tree changes while the game is running ? like hot reload in godot debugger ?
it is possible but need some more work with the plugins.


if just press save anywhere and it is save is the point of this fix.
i just push to master you can test the latest fix.

**Comment by fian46** [comment]
i have submit this plugins to asset store. it still pending. no one use it, so i think it is fine.

**Comment by davord45** [comment]
I mean when you press the run button,if i havent saved the tree before for it to get saved.

**Comment by davord45** [comment]
Real time tree editing would be nice but maybe when you develop the plugin some more in future versions.

**Comment by davord45** [comment]
Also could there be a possibility to add like dynamic parameters,so that state function can change the parameters or add some?

**Comment by fian46** [comment]
yes it is supposed to be fixed. i test it seams work.

**Comment by fian46** [comment]
like blackboard ?

**Comment by fian46** [comment]
> Also could there be a possibility to add like dynamic parameters,so that state function can change the parameters or add some?Maybe thats a thing for future versions.

is this dynamic parameter can be accessed by other task ? like global variable ?

**Comment by davord45** [comment]
Yeah something like that,so that its not limited to only one script

**Comment by davord45** [comment]
Save works now,thanks!

**Comment by davord45** [comment]
Now there is no hiccups,smooth workflow overall.

**Comment by fian46** [comment]
Finally it's fixed properly. Thanks for the help.
