### ISSUE TITLE
Asset Library version still has a save bug

### ISSUE THREAD

**Issue by davord45** [fian46/addons-btree#27]
Hi fian46,i tested the asset library addon,and there its not updated with the save fix,github version works just fine.
![slika](https://user-images.githubusercontent.com/70846358/93569813-63047780-f992-11ea-9b92-34a3785f87cc.png)
![slika](https://user-images.githubusercontent.com/70846358/93569831-6992ef00-f992-11ea-96b0-b5c36c61edb0.png)
This is downloaded when i press Download button on Asset Library.
![slika](https://user-images.githubusercontent.com/70846358/93570600-8aa80f80-f993-11ea-9a69-c24bae006e34.png)

**Comment by davord45** [comment]
Btw maybe you could put all the videos you have on BTREE,cause current one is only for debugging.

**Comment by fian46** [comment]
I am not sure. I am already put the lastest commit hash in the submission page.

**Comment by davord45** [comment]
Maybe it hasnt updated yet,cause i only saw your addoj today even though you posted it yesterday

**Comment by fian46** [comment]
Can you confirm this by download it from godot web page ? The hash must be 83a435e315b88a82007c7a5efa808019b6eda3e6

**Comment by davord45** [comment]
I will look at it in about hour or two,need some shit to do

**Comment by fian46** [comment]
that is fine i have check it is not a bug. the engine need to restart after downloading the asset. it is bug in gdscript cyclic loader.

**Comment by davord45** [comment]
Ah my bad dude.
