### ISSUE TITLE
Redo does not work

### ISSUE THREAD

**Issue by davord45** [fian46/addons-btree#35]
Hi fian46.
Nice job on the undo feature.
![image](https://user-images.githubusercontent.com/70846358/94834128-434c6500-0410-11eb-9ca6-e72741977480.png)
![image](https://user-images.githubusercontent.com/70846358/94834145-48111900-0410-11eb-810b-4779c5f7bce5.png)
That one works great,but when i try to redo with CTRL+Y it does not work.

**Comment by fian46** [comment]
I think it is ctrl shift z for redo. Pls check your key bind in godot editor setting

**Comment by davord45** [comment]
Yeah it is,works great,nice job dude!
