### ISSUE TITLE
Add option for Search Node Next and Search Node Previous

### ISSUE THREAD

**Issue by davord45** [fian46/addons-btree#37]
Hey fian46.
Could you add for Search Node bar to have arrows or something to go to next/previous node with the same function name?
Cant seem to find how to do it now. Just a little speed to the workflow like you did for jump to source.

**Comment by fian46** [comment]
you can test it in 1.1.8-beta

**Comment by davord45** [comment]
Arrows go thru all nodes,regardless of the name.

**Comment by fian46** [comment]
Oh you mean search only function name and not the entire node tree ?.  But i like it to be able to search everything too.

**Comment by davord45** [comment]
Well can you make a shortcut to jump to next node and jump to previous,but keep search for function named? Cause that is when im trying to find something specific.Going threw entire tree when its a big tree is kind of tedious

**Comment by fian46** [comment]
So you're suggesting the search is only for function name only ?

**Comment by davord45** [comment]
Yes,and that some hotkey is jump to next and previous nodes,cause i dont see why xou would need to search for that.You can jump from selected.

**Comment by davord45** [comment]
New commit fixes work great!
