### ISSUE TITLE
add an "init" callback for a task node.

### ISSUE THREAD

**Issue by JustusPan** [fian46/addons-btree#41]
The usage of this feature could be summarized as following quotation.
https://www.gamasutra.com/blogs/ChrisSimpson/20140717/221339/Behavior_trees_for_AI_How_they_work.php

> init - Called the first time a node is visited by its parent during its parents execution. For example a sequence will call this when its the node’s turn to be processed. It will not be called again until the next time the parent node is fired after the parent has finished processing and returned a result to its parent. This function is used to initialise the node and start the action the node represents. Using our walk example, it will retrieve the parameters and perhaps initiate the pathfinding job.

> process - This is called every tick of the behaviour tree while the node is processing. If this function returns Success or Failure, then its processing will end and the result passed to its parent. If it returns Running it will be reprocessed next tick, and again and again until it returns a Success or Failure. In the Walk example, it will return Running until the pathfinding either succeeds or fails.

**Comment by fian46** [comment]
you can use the master branch. it have is_init() function in control flow, if it returning true then it is init call, false is otherwise. currently i have no time to publish it in asset store you can use master branch, it is currently in version 1.1.8 and already stable, asset store is behind.

**Comment by JustusPan** [comment]
my version is 1.1.8. but I didn't find this is_init() function. any example?

**Comment by davord45** [comment]
I think its added in the new commit,version 1.1.8 is older

**Comment by fian46** [comment]
Sorry it's in latest commit. My bad probably i should bump the version.

**Comment by JustusPan** [comment]
`task.is_init()` works in the latest version. Thanks.
