### ISSUE TITLE
Script Error

### ISSUE THREAD

**Issue by Gafta** [fian46/addons-btree#42]
I wanted to try your addon but get the following Error while opening the godot project:
SCRIPT ERROR: _process: Invalid call. Nonexistent function 'is_playing_scene' in base 'EditorInterface'.
          At: res://addons/btree/init.gd:144
I use Godot v3.2.2 stable_win64 and Version 1.1.8 of your plugin.

**Comment by fian46** [comment]
You need to upgrade godot to 3.2.3 stable. I am sorry but that function is essential so godot base version need to upgrade as well to 3.2.3 stable

**Comment by Gafta** [comment]
Oh, I didnt realise. Thats an easy fix, thanks for the heads up.

**Comment by fian46** [comment]
Your welcome
