### ISSUE TITLE
support "Succeeder" Node

### ISSUE THREAD

**Issue by JustusPan** [fian46/addons-btree#44]
> A succeeder will always return success, irrespective of what the child node actually returned. These are useful in cases where you want to process a branch of a tree where a failure is expected or anticipated, but you don’t want to abandon processing of a sequence that branch sits on. The opposite of this type of node is not required, as an inverter will turn a succeeder into a ‘failer’ if a failure is required for the parent.

**Comment by davord45** [comment]
You have a mute node which does the same

**Comment by JustusPan** [comment]
Thank you for the information, that's exactly what I need. @davord45
