### ISSUE TITLE
is_init() hasn't been re-called if disable and enable a tree at runtime

### ISSUE THREAD

**Issue by JustusPan** [fian46/addons-btree#45]
when I use "enable" property to disable/enable a tree at runtime. the re-actived tree didn't restart its traverse. and continue to evaluate the task func when its disable happen, and the is_init() hasn't been called at this time.

need an option to decide whether to restart a tree completely if it's recovered from disable status.

**Comment by fian46** [comment]
Maybe i can add restart and resume function. Restart will enable tree and reset completely but resume just continue like old behavior.

**Comment by JustusPan** [comment]
That will be a good solution. If this two mode are selectable in the inspector that will be good.
each time when we enable a tree from disabled status, it will pick one of restart or resume function according to user's setting

**Comment by fian46** [comment]
hey it is already in master you can do restart by changing  on_enable to restart to make this possible
