### ISSUE TITLE
Thanks for the addon :D

### ISSUE THREAD

**Issue by warriormaster12** [fian46/addons-btree#46]
Hello friends,
I have created this issue because I would like to thank you for creating this addon. It's really good especially for a guy who comea from Unreal Engine world.

I know obviously that this addon is still in beta but I would like to provide some feedback. 

The biggest problem currently is that the documentation doesn't cover all of the btree nodes, which limits how much a user can do with them.

For example I want to use a selector in my behavior tree to switch between different states but I have no idea how to call the selector to switch states.

I have been able to work around the issue by switching trees based on state but it would be nicer to have selector working. Other than that, I like the addon and I hope that you will continue developing it.

Thank you and have a nice day :D

**Comment by fian46** [comment]
Hi. 
This plugins always assume you have known behavior tree before. In behavior tree you can't change how a node behave. It is a pattern. selector node for instance will pick the first child that trigger succeed in control flow and trigger it self as succeed or failed when there's no node is succeed. If i can recommend this tutorial is very good how to use this addon https://youtu.be/HEnKCJ9AQ9E.

**Comment by warriormaster12** [comment]
Hi, 
thanks for clarifying how selector works in Btree. It's a bit different compared to how it works in Unreal but I quickly figured out. You could probably put the tutorial link into the readme file for newcomers. 

Anyways, good luck with the project! I truly wish that more people will you use this and have a nice day :)
