### ISSUE TITLE
Feature request, label for decorators.

### ISSUE THREAD

**Issue by TrevSaysHi** [fian46/addons-btree#47]
Hello! I would like to be able to add a description of sorts for general decorators.
Something akin to this.
![image](https://user-images.githubusercontent.com/65880004/108629620-68c12600-7426-11eb-92d2-728fe25a5fc4.png)
I find when the trees sequences gets big/nested it would be nice to have a quick way to know what each sequence does.

I started to work on adding one, but somewhere in loading the data back in the editor my trees got corrupted haha so I reverted it all back.

**Comment by fian46** [comment]
sure it can be done but are you have tried minimize the node first ? (select a node and press CTRL + SHIFT + M) you can put label too.

**Comment by TrevSaysHi** [comment]
I did not know you could do that! I did try to minimize the node but I cannot resize it for some reason. It just looks like this.
![image](https://user-images.githubusercontent.com/65880004/108703309-10466300-74d0-11eb-9855-3c4df7493a74.png)
If possible I do think having a description on the decorator would be nice, but if I can resize the minimized node that would be sufficient.

**Comment by TrevSaysHi** [comment]
I was able to resize it after re opening the BTREE, not sure why it didn't let me when I created it. Probably user error. I will close this story as this works!

**Comment by fian46** [comment]
yes minim node cannot resize is a bug. i am already fixing it in master. you can download latest release.

**Comment by TrevSaysHi** [comment]
Awesome! thanks for making this its super helpful!
