### ISSUE TITLE
Invalid call. Nonexistent function 'write' in base 'Control (client_debugger.gd)'.

### ISSUE THREAD

**Issue by Azuna1** [fian46/addons-btree#63]
As soon as i enable the plugin (cloned from repo) my output is spammed with:
 res://addons/btree/Editor/rtree.gd:200 - Invalid call. Nonexistent function 'write' in base 'Control (client_debugger.gd)'.

running godot 3.4

**Comment by fian46** [comment]
I will looking in to it. I never test it for godot version 3.4

**Comment by francoisdlt** [comment]
Running B-Tree 1.1.9 on Godot 3.4.stable.mono under macOS 12.0.1 with no error.

**Comment by Azuna1** [comment]
Seems like the issue was, that we disabled the websocket module:
module_websocket_enabled=no
